// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgIlDu7W2H_t0zbUmDf8bXi8tNtRX8Ov4',
    appId: '1:392956117729:web:e5f87cabe993a97a23eda0',
    messagingSenderId: '392956117729',
    projectId: 'smart-pos-480c5',
    authDomain: 'smart-pos-480c5.firebaseapp.com',
    storageBucket: 'smart-pos-480c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5RRYaEq0ow_Z2DEzdXBemWaYepHGcUrY',
    appId: '1:392956117729:android:48ac016ebe619cfa23eda0',
    messagingSenderId: '392956117729',
    projectId: 'smart-pos-480c5',
    storageBucket: 'smart-pos-480c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwRK63p3fva5XZzfFTabQdE14wgtmsubU',
    appId: '1:392956117729:ios:7b693d68f5bd10a123eda0',
    messagingSenderId: '392956117729',
    projectId: 'smart-pos-480c5',
    storageBucket: 'smart-pos-480c5.firebasestorage.app',
    iosBundleId: 'com.example.smartPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwRK63p3fva5XZzfFTabQdE14wgtmsubU',
    appId: '1:392956117729:ios:7b693d68f5bd10a123eda0',
    messagingSenderId: '392956117729',
    projectId: 'smart-pos-480c5',
    storageBucket: 'smart-pos-480c5.firebasestorage.app',
    iosBundleId: 'com.example.smartPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgIlDu7W2H_t0zbUmDf8bXi8tNtRX8Ov4',
    appId: '1:392956117729:web:1b0626f9b0b3667e23eda0',
    messagingSenderId: '392956117729',
    projectId: 'smart-pos-480c5',
    authDomain: 'smart-pos-480c5.firebaseapp.com',
    storageBucket: 'smart-pos-480c5.firebasestorage.app',
  );
}
