import 'package:flutter/material.dart';

class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // Existing translations
      'app_title': 'Point of Sale',
      'login': 'Login',
      'signup': 'Sign Up',
      'username': 'Username',
      'password': 'Password',
      'service_charge_amount': 'Service Charge Amount',
      'confirm_password': 'Confirm Password',
      'enter_username': 'Enter username',
      'enter_password': 'Enter password',
      'username_required': 'Username is required',
      'password_required': 'Password is required',
      'password_mismatch': 'Password doesn\'t match',
      'login_error': 'Username or password is incorrect',
      'register_account': 'Register New Account',
      'have_account': 'Already have an account?',
      'dont_have_account': 'Don\'t have an account?',
      'apply_service_charge': 'Apply Service Charge',
      'settings': 'Settings',
      'language': 'Language',
      'checkout': 'Checkout',
      'inventory': 'Inventory',
      'add_item': 'Add Item',
      'fetch': 'Fetch',
      'order': 'Order',
      'shifts': 'Shifts',
      'search': 'Search',
      'welcome': 'Welcome',
      'open_shift': 'Open Shift',
      'close_shift': 'Close Shift',
      'back': 'Back',
      'hold': 'Hold',
      'get': 'Get',
      'quantity': 'QTY',
      'item': 'ITEM',
      'price': 'PRICE',
      'subtotal': 'Subtotal',
      'service_charge': 'Service Charge',
      'tax': 'Tax',
      'total': 'Total',
      'shift_opened_at': 'Shift opened at {time}',
      'shift_closed_at': 'Shift closed at {time}',
      'no_shift_to_close': 'No shift to close',
      'no_items_to_checkout': 'No items to checkout',
      'order_checked_out_success': 'Order checked out successfully',
      'failed_to_checkout': 'Failed to checkout: {error}',
      'failed_to_fetch_categories': 'Failed to fetch categories: {error}',
      'failed_to_fetch_subcategories': 'Failed to fetch subcategories: {error}',
      'item_removed_from_order': '{item_name} removed from order',
      'undo': 'Undo',
      'orders_table': 'Orders Table',
      'clear_database': 'Clear Database',
      'select_held_order': 'Select Held Order',
      'no_orders_found': 'No orders found.',
      'number': 'Number',
      'order_number': 'Order Number',
      'date': 'Date',
      'total_price': 'Total Price',
      'items': 'Items',
      'failed_to_load_orders': 'Failed to load orders.',
      'failed_to_delete_item': 'Failed to delete item.',
      'database_cleared': 'Database cleared!',
      'shift_table': 'Shift Table',
      'clear_shifts': 'Clear Shifts',
      'clear_shifts_confirmation': 'Are you sure you want to clear all shifts?',
      'clear': 'Clear',
      'no_shift_data_available': 'No shift data available.',
      'error': 'Error',
      'id': 'Id',
      'day_code': 'Day Code',
      'day_shift_begin': 'Day Shift Begin',
      'day_shift_end': 'Day Shift End',
      'night_shift_begin': 'Night Shift Begin',
      'night_shift_end': 'Night Shift End',
      'open_shift_time': 'Open Shift',
      'close_shift_time': 'Close Shift',
      'extra_time': 'Extra Time',
      // New translations from MyHomePage
      'failed_to_sync_data': 'Failed to sync data: {error}',
      'failed_to_open_shift': 'Failed to open shift',
      'final_cash_count': 'Final Cash Count',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'failed_to_close_shift': 'Failed to close shift',
      'no_active_shift': 'No active shift',
      'item_added_to_order': '{item_name} added to order',
      'fill_all_fields': 'Please fill all fields',
      'invalid_price': 'Invalid price',
      'item_updated': 'Item {item_name} updated',
      'failed_to_update_item': 'Failed to update item: {error}',
      'failed_to_save_item': 'Failed to save item: {error}',
      'admin_only_action': 'This action is for admins only',
      'confirm_delete': 'Confirm Delete',
      'delete_item_confirm': 'Are you sure you want to delete {item_name}?',
      'delete': 'Delete',
      'item_deleted': 'Item deleted',
      'refresh_data': 'Refresh Data',
      'logout': 'Logout',
      'no_categories': 'No categories available',
      'select_category': 'Select a category',
      'no_items_in_order': 'No items in order',
      'pay_with_cash': 'Pay with Cash',
      'pay_with_card': 'Pay with Card',
      'edit_item': 'Edit Item',
      'delete_item': 'Delete Item',
      'new_item': 'New Item',
      'item_name': 'Item Name',
      'barcode': 'Barcode',
      'category': 'Category',
      'update': 'Update',
      'save': 'Save',
      // New translations from ShiftReportScreen
      'shift_reports': 'Shift Reports',
      'failed_to_load_shifts': 'Failed to load shifts',
      'select_date_range': 'Select Date Range',
      'clear_filters': 'Clear Filters',
      'toggle_time_format': 'Toggle Time Format',
      'no_shifts_found': 'No shifts found',
      'status': 'Status',
      'cash_count': 'Cash Count',
      'error_loading_transactions': 'Error loading transactions',
      'delete_category_confirm':
          'Are you sure you want to delete {category_name}?',
      'no_transactions': 'No transactions',
      'total_sales': 'Total Sales',
      'cash_sales': 'Cash Sales',
      'visa_sales': 'Visa Sales',
      'transaction': 'Transaction',
      // New translations from OrdersTable
      'failed_to_clear_database': 'Failed to clear database',
      'order_history': 'Order History',
      'refresh': 'Refresh',
      // New translations from SettingsScreen
      'appearance': 'Appearance',
      'accounts': 'Accounts',
      'fill_category_name': 'Please fill category name',
      'category_added': 'Category added',
      'failed_to_save_category': 'Failed to save category: {error}',
      'item_merged': 'Item merged',
      'item_added': 'Item added',
      'no_barcode_detected': 'No barcode detected',
      'invalid_barcode_format': 'Invalid barcode format',
      'barcode_already_exists': 'Barcode already exists for {item_name}',
      'similar_item_found': 'Similar item found',
      'merge_or_separate': 'Merge with {item_name} or add as separate?',
      'add_as_new': 'Add as New',
      'merge': 'Merge',
      'item_management': 'Item Management',
      'manage_items_categories': 'Manage Items & Categories',
      'add_category': 'Add Category',
      'scan_new_item': 'Scan New Item',
      'scan_barcode_prompt': 'Please scan the barcode',
      'category_name': 'Category Name',
      'theme': 'Theme',
      'account': 'Account',
      'logout_confirmation': 'Logout Confirmation',
      'logout_question': 'Are you sure you want to logout?',
      'no_items_to_hold': 'No items to hold',
      'order_held': 'Order held',
      'no_held_orders': 'No held orders',
      'order_retrieved': 'Order retrieved',
      'item_not_found': 'Item not found',
      'add_new_item': 'Add New Item',
      'initial_stock_quantity': 'Initial Stock Quantity',
      'initial_stock_must_be_non_negative':
          'Initial stock must be a non-negative number',
      'clear_all_orders': 'Clear All Orders',
      'out_of_stock': 'Item is out of stock',
      'no_store_id': 'No store ID available',
    },
    'ar': {
      // Existing translations
      'app_title': 'نقطة البيع',
      'login': 'تسجيل الدخول',
      'signup': 'التسجيل',
      'username': 'اسم المستخدم',
      'password': 'كلمة المرور',
      'confirm_password': 'تأكيد كلمة المرور',
      'enter_username': 'أدخل اسم المستخدم',
      'enter_password': 'أدخل كلمة المرور',
      'username_required': 'اسم المستخدم مطلوب',
      'password_required': 'كلمة المرور مطلوبة',
      'password_mismatch': 'كلمة المرور غير متطابقة',
      'login_error': 'اسم المستخدم أو كلمة المرور غير صحيحة',
      'register_account': 'تسجيل حساب جديد',
      'select_held_order': 'اختر الطلب المعلق',
      'delete_category_confirm': 'هل انت متاكد من مسح {category_name}  ',
      'have_account': 'هل لديك حساب؟',
      'dont_have_account': 'ليس لديك حساب؟',
      'apply_service_charge': 'تفعيل ضريبة الخدمة',
      'Home': 'الرئيسيه',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'checkout': 'الدفع',
      'inventory': 'المخزون',
      'add_item': 'إضافة عنصر',
      'fetch': 'جلب',
      'order': 'الطلب',
      'shifts': 'الورديات',
      'search': 'بحث',
      'welcome': 'مرحبًا',
      'open_shift': 'فتح الوردية',
      'close_shift': 'إغلاق الوردية',
      'back': 'رجوع',
      'hold': 'تعليق',
      'get': 'استرداد',
      'quantity': 'الكمية',
      'item': 'الصنف',
      'price': 'السعر',
      'subtotal': 'المجموع الفرعي',
      'service_charge': 'رسوم الخدمة',
      'tax': 'الضريبة',
      'total': 'الإجمالي',
      'shift_opened_at': 'تم فتح الوردية في {time}',
      'shift_closed_at': 'تم إغلاق الوردية في {time}',
      'no_shift_to_close': 'لا توجد وردية للإغلاق',
      'no_items_to_checkout': 'لا توجد عناصر للدفع',
      'order_checked_out_success': 'تم دفع الطلب بنجاح',
      'failed_to_checkout': 'فشل الدفع: {error}',
      'failed_to_fetch_categories': 'فشل جلب الفئات: {error}',
      'failed_to_fetch_subcategories': 'فشل جلب الفئات الفرعية: {error}',
      'item_removed_from_order': 'تم إزالة {item_name} من الطلب',
      'undo': 'تراجع',
      'orders_table': 'جدول الطلبات',
      'clear_database': 'مسح قاعدة البيانات',
      'no_orders_found': 'لم يتم العثور على طلبات.',
      'number': 'الرقم',
      'order_number': 'رقم الطلب',
      'date': 'التاريخ',
      'total_price': 'السعر الإجمالي',
      'items': 'الأصناف',
      'failed_to_load_orders': 'فشل تحميل الطلبات.',
      'failed_to_delete_item': 'فشل حذف الصنف.',
      'database_cleared': 'تم مسح قاعدة البيانات!',
      'shift_table': 'جدول الورديات',
      'clear_shifts': 'مسح الورديات',
      'clear_shifts_confirmation': 'هل أنت متأكد من مسح جميع الورديات؟',
      'clear': 'مسح',
      'no_shift_data_available': 'لا توجد بيانات ورديات متاحة.',
      'error': 'خطأ',
      'id': 'المعرف',
      'day_code': 'كود اليوم',
      'day_shift_begin': 'بداية وردية النهار',
      'day_shift_end': 'نهاية وردية النهار',
      'night_shift_begin': 'بداية وردية الليل',
      'night_shift_end': 'نهاية وردية الليل',
      'open_shift_time': 'فتح الوردية',
      'close_shift_time': 'إغلاق الوردية',
      'extra_time': 'الوقت الإضافي',
      // New translations from MyHomePage
      'failed_to_sync_data': 'فشل مزامنة البيانات: {error}',
      'failed_to_open_shift': 'فشل فتح الوردية',
      'final_cash_count': 'عد النقود النهائي',
      'cancel': 'إلغاء',
      'confirm': 'تأكيد',
      'failed_to_close_shift': 'فشل إغلاق الوردية',
      'no_active_shift': 'لا توجد وردية نشطة',
      'item_added_to_order': 'تم إضافة {item_name} إلى الطلب',
      'fill_all_fields': 'يرجى ملء جميع الحقول',
      'invalid_price': 'السعر غير صالح',
      'item_updated': 'تم تحديث الصنف {item_name}',
      'failed_to_update_item': 'فشل تحديث الصنف: {error}',
      'failed_to_save_item': 'فشل حفظ الصنف: {error}',
      'admin_only_action': 'هذا الإجراء للمديرين فقط',
      'confirm_delete': 'تأكيد الحذف',
      'delete_item_confirm': 'هل أنت متأكد من حذف {item_name}؟',
      'delete': 'حذف',
      'item_deleted': 'تم حذف الصنف ',
      'refresh_data': 'تحديث البيانات',
      'logout': 'تسجيل الخروج',
      'no_categories': 'لا توجد فئات متاحة',
      'select_category': 'اختر فئة',
      'no_items_in_order': 'لا توجد أصناف في الطلب',
      'service_charge_amount': 'سعر الخدمة',
      'pay_with_cash': 'الدفع نقدًا',
      'pay_with_card': 'الدفع بالبطاقة',
      'edit_item': 'تعديل الصنف',
      'delete_item': 'حذف الصنف',
      'new_item': 'صنف جديد',
      'item_name': 'اسم الصنف',
      'barcode': 'الباركود',
      'category': 'الفئة',
      'update': 'تحديث',
      'save': 'حفظ',
      // New translations from ShiftReportScreen
      'shift_reports': 'تقارير الورديات',
      'failed_to_load_shifts': 'فشل تحميل الورديات',
      'select_date_range': 'اختر نطاق التاريخ',
      'clear_filters': 'مسح الفلاتر',
      'toggle_time_format': 'تبديل تنسيق الوقت',
      'no_shifts_found': 'لم يتم العثور على ورديات',
      'status': 'الحالة',
      'cash_count': 'عد النقود',
      'error_loading_transactions': 'خطأ في تحميل المعاملات',
      'no_transactions': 'لا توجد معاملات',
      'total_sales': 'إجمالي المبيعات',
      'cash_sales': 'المبيعات النقدية',
      'visa_sales': 'مبيعات فيزا',
      'transaction': 'معاملة',
      // New translations from OrdersTable
      'failed_to_clear_database': 'فشل مسح قاعدة البيانات',
      'order_history': 'سجل الطلبات',
      'refresh': 'تحديث',
      // New translations from SettingsScreen
      'appearance': 'المظهر',
      'accounts': 'الحسابات',
      'fill_category_name': 'يرجى ملء اسم الفئة',
      'category_added': 'تم إضافة الفئة',
      'failed_to_save_category': 'فشل حفظ الفئة: {error}',
      'item_merged': 'تم دمج الصنف',
      'item_added': 'تم إضافة الصنف',
      'no_barcode_detected': 'لم يتم اكتشاف باركود',
      'invalid_barcode_format': 'تنسيق الباركود غير صالح',
      'barcode_already_exists': 'الباركود موجود بالفعل لـ {item_name}',
      'similar_item_found': 'تم العثور على صنف مشابه',
      'merge_or_separate': 'دمج مع {item_name} أو إضافة كمنفصل؟',
      'add_as_new': 'إضافة كجديد',
      'merge': 'دمج',
      'item_management': 'إدارة الأصناف',
      'manage_items_categories': 'إدارة الأصناف والفئات',
      'add_category': 'إضافة فئة',
      'scan_new_item': 'مسح صنف جديد',
      'scan_barcode_prompt': 'يرجى مسح الباركود',
      'category_name': 'اسم الفئة',
      'theme': 'الثيم',
      'account': 'الحساب',
      'logout_confirmation': 'تأكيد تسجيل الخروج',
      'logout_question': 'هل أنت متأكد من تسجيل الخروج؟',
      'no_items_to_hold': 'لا توجد عناصر للتعليق',
      'order_held': 'تم تعليق الطلب',
      'no_held_orders': 'لا توجد طلبات معلقة',
      'order_retrieved': 'تم استرداد الطلب',
      'item_not_found': 'الصنف غير موجود',
      'add_new_item': 'إضافة صنف جديد',
      'initial_stock_quantity': 'الكمية الابتدائية للمخزون',
      'initial_stock_must_be_non_negative':
          'يجب أن تكون الكمية الابتدائية للمخزون رقمًا غير سالب',
      'clear_all_orders': 'مسح جميع الطلبات',
      'out_of_stock': 'الصنف نفد من المخزون',
      'no_store_id': 'لا يوجد معرف للمتجر',
    },
  };

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final instance = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );
    return instance ?? AppLocalizations('en');
  }

  final String _locale;

  AppLocalizations(this._locale);

  String translate(String key, {Map<String, String>? params}) {
    String? localizedValue =
        _localizedValues[_locale]?[key] ?? _localizedValues['en']?[key];
    if (localizedValue == null) return key;
    if (params != null) {
      params.forEach((paramKey, paramValue) {
        localizedValue = localizedValue!.replaceAll('{$paramKey}', paramValue);
      });
    }
    return localizedValue!;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale.languageCode);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
