// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb6lnM2WWwYWQYDvCt-P5fCEAf-uHQ9EA',
    appId: '1:968106175855:web:37a4167580c9f5dfc8cc9a',
    messagingSenderId: '968106175855',
    projectId: 'point-of-service-f06f6',
    authDomain: 'point-of-service-f06f6.firebaseapp.com',
    storageBucket: 'point-of-service-f06f6.firebasestorage.app',
    measurementId: 'G-ZQ2CF20PVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx1AFQF7ooV1_Hx5esSuBPYcFGi0jcjBE',
    appId: '1:968106175855:android:80804c7a5e0cc51cc8cc9a',
    messagingSenderId: '968106175855',
    projectId: 'point-of-service-f06f6',
    storageBucket: 'point-of-service-f06f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATzO8dsxAMfvirs9c5dlDK4iPnZM5OXf0',
    appId: '1:968106175855:ios:4cec7aa559945d2bc8cc9a',
    messagingSenderId: '968106175855',
    projectId: 'point-of-service-f06f6',
    storageBucket: 'point-of-service-f06f6.firebasestorage.app',
    iosBundleId: 'com.smartup.zpos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATzO8dsxAMfvirs9c5dlDK4iPnZM5OXf0',
    appId: '1:968106175855:ios:4cec7aa559945d2bc8cc9a',
    messagingSenderId: '968106175855',
    projectId: 'point-of-service-f06f6',
    storageBucket: 'point-of-service-f06f6.firebasestorage.app',
    iosBundleId: 'com.smartup.zpos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb6lnM2WWwYWQYDvCt-P5fCEAf-uHQ9EA',
    appId: '1:968106175855:web:cb0d0efcaefeb991c8cc9a',
    messagingSenderId: '968106175855',
    projectId: 'point-of-service-f06f6',
    authDomain: 'point-of-service-f06f6.firebaseapp.com',
    storageBucket: 'point-of-service-f06f6.firebasestorage.app',
    measurementId: 'G-XBMTT5WP9W',
  );
}
